version: "3.3"
services:

  server1:
    image: mmvv/tsu_server:latest
    ports:
      - "7755:7755/udp"
      - "7756:7756/udp"
    environment:
     - SERVER_NAME=dc-tsu-1

  server2:
    image: mmvv/tsu_server:latest
    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
    environment:
     - SERVER_NAME=dc-tsu-2
     - TSU_PORT=7777

